server:
  port: 8088

spring:
  web:
    resources:
      static-locations:
        - "classpath:/META-INF/resources/"
        - "classpath:/resources/"
        - "classpath:/static/"
        - "classpath:/public/"
        - "classpath:/templates/"
  config:
    location: "classpath:/application.yml"
    additional-location: "classpath:/application.yml"
    import: "classpath:/application.yml"